version: "3.9"
services:
  metaserver:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/metaserver
    command: bash -c "
      alembic upgrade head
      && pytest
      && uvicorn metaserver.api:app --host 0.0.0.0 --port 80
      "
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
