"""Add UserStats table

Revision ID: 4dab9b45423b
Revises: 3b6a2db249ae
Create Date: 2022-11-05 21:02:43.573564+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "4dab9b45423b"
down_revision = "3b6a2db249ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userstats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("matches_played", sa.Integer(), nullable=False),
        sa.Column("skill_rating", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "server_id"),
    )
    op.alter_column(
        "clan", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "clanskinlink", "skin_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "clanskinlink", "clan_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("emailtoken", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("emailtoken", "key", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "server", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "server", "current_player_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("server", "current_map", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "skin", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "user", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "userclanlink", "clan_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "userclanlink", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("userclanlink", "rank", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "userskinlink", "skin_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "userskinlink", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userskinlink", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "userskinlink", "skin_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("userclanlink", "rank", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "userclanlink", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "userclanlink", "clan_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.alter_column(
        "skin", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.alter_column("server", "current_map", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "server", "current_player_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "server", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.alter_column("emailtoken", "key", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("emailtoken", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "clanskinlink", "clan_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "clanskinlink", "skin_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "clan", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.drop_table("userstats")
    # ### end Alembic commands ###
