"""Add current_map field to Server

Revision ID: 58211f62790d
Revises: 8720c1ebff2b
Create Date: 2022-08-07 08:16:08.777873+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "58211f62790d"
down_revision = "8720c1ebff2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server",
        sa.Column("current_map", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "current_map")
    # ### end Alembic commands ###
