"""Add deleted and deleted_reason fields to server

Revision ID: 8720c1ebff2b
Revises: a39807b0ac7f
Create Date: 2022-08-05 16:30:09.107190+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "8720c1ebff2b"
down_revision = "a39807b0ac7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("deleted", sa.DateTime(), nullable=True))
    op.add_column(
        "server",
        sa.Column("deleted_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "deleted_reason")
    op.drop_column("server", "deleted")
    # ### end Alembic commands ###
