"""Initial Migration

Revision ID: a39807b0ac7f
Revises: 
Create Date: 2022-08-05 16:23:23.465751+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "a39807b0ac7f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clan",
        sa.Column("tag", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("tag"),
    )
    op.create_table(
        "skin",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("verified_email", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.Column("deleted_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "clanskinlink",
        sa.Column("skin_id", sa.Integer(), nullable=True),
        sa.Column("clan_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skin_id"],
            ["skin.id"],
        ),
        sa.PrimaryKeyConstraint("skin_id", "clan_id"),
    )
    op.create_table(
        "server",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("host_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_player_count", sa.Integer(), nullable=True),
        sa.Column("max_player_count", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userclanlink",
        sa.Column("clan_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("invited", sa.DateTime(), nullable=False),
        sa.Column("joined", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("clan_id", "user_id"),
    )
    op.create_table(
        "userskinlink",
        sa.Column("skin_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["skin_id"],
            ["skin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("skin_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userskinlink")
    op.drop_table("userclanlink")
    op.drop_table("server")
    op.drop_table("clanskinlink")
    op.drop_table("user")
    op.drop_table("skin")
    op.drop_table("clan")
    # ### end Alembic commands ###
