"""Add icon to Clan and add port to Server

Revision ID: cf975c110d95
Revises: d2770f775b33
Create Date: 2022-08-28 20:40:37.946417+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "cf975c110d95"
down_revision = "d2770f775b33"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clan", sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("server", sa.Column("port", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "port")
    op.drop_column("clan", "icon")
    # ### end Alembic commands ###
